### ISSUE TITLE
Having a issues installing the plugins

### ISSUE THREAD

**Issue by andrewchumchal** [PhAzE-Variance/unRAID#10]
Everytime i try to install a plugin i get this error 
`
plugin: installing: /boot/config/plugins/Sonarr.plg`
`Installing Sonarr plugin`
`Checking for current bundle files`
`Control file: Not Found`
`Dependency file: Not found`
`Mono file: Not found`
`Check OK!`
`Downloading new control file`
`Install failed: Unable to detect internet connection`
`plugin: run failed: /bin/bash retval: 1`

Do not  known how to fix it. I can ping outside network fine. Please help

Edit:
I can update other apps and plugins. Just cannot install this one or sickrage are the only ones i tried

**Comment by PhAzE-Variance** [comment]
From your unraid console, what do you see when you run the following:
timeout 5 wget --no-check-certificate -qST4 --spider "https://github.com/PhAzE-Variance" 2>&1 | grep HTTP | tail -1 | cut -f1 | awk '{print $NF}'

**Comment by andrewchumchal** [comment]
Thanks for your quick reply. When i put that in my unraid console. I got nothing back.  [![Capture1.jpg](https://s13.postimg.org/kxz33hxlz/Capture1.jpg)](https://postimg.org/image/dur7nvs6b/)

**Comment by PhAzE-Variance** [comment]
How about just this part:
wget --no-check-certificate -qST4 --spider "https://github.com/PhAzE-Variance"

The output should start with: HTTP/1.1 200 OK

If you see that, it means you can reach my repo but if not, your sever is unable to reach my repo.  Do you see anything odd in the output from the above command when you run it?

**Comment by andrewchumchal** [comment]
That command also comes up blank. Strange 
Any ideas why ?

**Comment by PhAzE-Variance** [comment]
Can you ping it from your server, and also try nslookup to see if you get an ip. Chances are your server is not getting the dns ressolved correctly.

**Comment by andrewchumchal** [comment]
I can net lookup and ping github.com fine 
[![Capture2.jpg](https://s17.postimg.org/t0ez6ynzj/Capture2.jpg)](https://postimg.org/image/us7y1v7cb/)

**Comment by PhAzE-Variance** [comment]
Ok, now try: telnet github.com 443

Does it open the connection and stay open or does it disconnect immediately?

**Comment by andrewchumchal** [comment]
It seems to stay open 
[![Capture3.jpg](https://s6.postimg.org/pkyd2la1t/Capture3.jpg)](https://postimg.org/image/50tj43ual/)

**Comment by PhAzE-Variance** [comment]
So, it's strange that you can resovle the DNS to an IP, ping it, telnet to it, but wget will not connect.

try:  wget --no-check-certificate -qO- "https://github.com/PhAzE-Variance"

You should see the code for the github web site dump on your screen.

**Comment by andrewchumchal** [comment]
That is correct. I do get the html dump
[![Capture4.jpg](https://s6.postimg.org/enx1dtna9/Capture4.jpg)](https://postimg.org/image/5sw73ayhp/)

**Comment by PhAzE-Variance** [comment]
So it is working.

What version of unraid are you running?
When you run: wget --help  -> do you see an option for capital S (print server code) and one for --spider?

**Comment by andrewchumchal** [comment]
I do have the option for wget -S and --spider. I'm running unRAID 6.2.1

**Comment by PhAzE-Variance** [comment]
ok so we need to figure out which wget option isn't playing nice. try the following until one stops showing results:

wget --no-check-certificate -qO- "https://github.com/PhAzE-Variance"
wget --no-check-certificate -q --spider "https://github.com/PhAzE-Variance"
wget --no-check-certificate -qS --spider "https://github.com/PhAzE-Variance"
wget --no-check-certificate -qST4 --spider "https://github.com/PhAzE-Variance"

**Comment by andrewchumchal** [comment]
1 output code.
[![WGet qO.jpg](https://s6.postimg.org/unfoxdjc1/WGet_q_O.jpg)](https://postimg.org/image/xhiuatli5/)
2 blank 
[![WGet q spider.jpg](https://s6.postimg.org/e0y4oaqe9/WGet_q_spider.jpg)](https://postimg.org/image/ob0jnjg9p/)
3 output code
[![3 WGET qS spider.jpg](https://s6.postimg.org/5wq0jk3z5/3_WGET_q_S_spider.jpg)](https://postimg.org/image/cn6hszr4t/)
4 blank 
[![4 WGET.jpg](https://s6.postimg.org/58h60m59d/4_WGET.jpg)](https://postimg.org/image/kh73edyxp/)

**Comment by andrewchumchal** [comment]
Any update on this ?

**Comment by PhAzE-Variance** [comment]
With it being intermittent, there isn't much more I can do since it should either never work, or always work.  If you try option 3 and 4 above over and over a few times, does it work every time on 3 and fail every time on 4?

**Comment by andrewchumchal** [comment]
It seems the error of the code pops up here 
`wget --no-check-certificate -qO "$CTRLFILES" "&controlURL;"
`

**Comment by andrewchumchal** [comment]
3 comes back always with the correct output

**Comment by andrewchumchal** [comment]
I was finally able to install the plugin by making some edits to your plg file :)

**Comment by PhAzE-Variance** [comment]
Excellent.  The difference between option 3 and 4 is the 4 second timeout.  Likely the response was talking longer than the timer.
