### ISSUE TITLE
Sonarr won't start

### ISSUE THREAD

**Issue by blindpet** [PhAzE-Variance/unRAID#5]
on Unraid 6.0.1, sonarr installs but service wont' start, I check the box ans specify /usr/local/Sonarr/AppData and click Apply and this error is thrown every time

WARNING: Your config directory is not persistent and WILL NOT survive a reboot. Please locate the directory on disk for persistency

**Comment by PhAzE-Variance** [comment]
You need to set your config folder to your cache drive or a local disk.

Somewhere in /mnt/cache or /mnt/disk1

/usr/local exists in the RAM drive made by Unraid and is wiped on each reboot.
