### ISSUE TITLE
Plexmediaserver unable to login

### ISSUE THREAD

**Issue by Beck162** [PhAzE-Variance/unRAID#7]
Recently I get a "Unable to login to PlexPass with above credentials"

on the PlexPass branch 0.9.15.2.1663-7efd046

Not sure if this is the correct place for this issue or not.

I haven't done anything new recently, but this and Sabnzbd have become really unstable lately.

Thanks for the hard work!

**Comment by Beck162** [comment]
I also get Start failed No PID created error when trying to restart them.

**Comment by PhAzE-Variance** [comment]
Fixed in last update.
